apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
  labels:
    app.kubernetes.io/part-of: taskflow
type: Opaque
stringData:
  POSTGRES_DB: taskflow
  POSTGRES_USER: taskflow_user
  POSTGRES_PASSWORD: "taskflow123"
  JWT_SECRET: "taskflow_jwt_secret_change_me_1234567890"
